version: '3'
services:
  caddy:
    container_name: caddy
    image: caddy
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend-dist:/frontend-dist
  backend:
    container_name: backend
    depends_on: 
      - postgres-db
    restart: unless-stopped
    build: ./backend
    ports:
     - 7777:7777
    env_file: ./.env
    environment:
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL=$GOOGLE_CALLBACK_URL
      - JWT_SECRET=$JWT_SECRET
      - JWT_ACCESS_TOKEN_EXPIRY=$JWT_ACCESS_TOKEN_EXPIRY
      - JWT_REFRESH_TOKEN_EXPIRY=$JWT_REFRESH_TOKEN_EXPIRY
      - WEB_REDIRECT_URL=$WEB_REDIRECT_URL
      - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
      - PORT=$PORT
      - ROOM_ID_PREFIX=$ROOM_ID_PREFIX
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
  postgres-db:
    image: postgres:16.1
    container_name: postgres-db
    env_file: ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  frontend:
    build: ./frontend
    container_name: frontend
